version: '3.7'

services:
  cache:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
  db:
    container_name: dynamodb
    image: amazon/dynamodb-local:latest
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal
    ports:
      - 8000:8000
